apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: kubernetes-java-mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ= #password
  MYSQL_USER: dGVzdHVzZXI= #testuser
  MYSQL_PASSWORD: dGVzdDEyMw== #test123
